spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-98.railway.app:7034/railway
    username: postgres
    password: Y7rwhU0GCB7IJdrHiDfr
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate