name: Deploy Application

on:
  push:
    branches: [main]
env:
    SPRING_DATASOURCE_URL: ${{ secrets.IP_ECS2 }}
    SPRING_DATASOURCE_USERNAME: ${{ secrets.USERNAME_POSTGRES }}
    SPRING_DATASOURCE_PASSWORD: ${{ secrets.PASSWORD_POSTGRES }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Grant execute permissions to Gradlew
        run: chmod +x ./gradlew

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build project
        run: ./gradlew build
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t rbettarelli/deploy_todolist .
      - name: Push image docker
        run: docker push rbettarelli/deploy_todolist

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull img from docker hub
        run: docker pull rbettarelli/deploy_todolist:latest
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name deploy_todolist rbettarelli/deploy_todolist
